tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
brew "anyenv"
brew "php"
brew "composer"
brew "jq"
brew "tree"
mas "Slack", id: 803453959
# failed
# mas "Trello", id: 1278508951
# mas 'Kindle', id: 405399194
# cask "toggl-track"

cask "authy"
cask "docker"
cask "iterm2"
cask "postman"
cask "sequel-ace"
cask "visual-studio-code"
cask "google-chrome"
cask "kindle"
